In [1]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


# 迴歸分析
用UCI波士頓房價資料做迴歸分析
https://archive.ics.uci.edu/ml/datasets/housing

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.datasets import load_boston

### 匯入資料

In [3]:
boston = load_boston()

In [4]:
type(boston)

sklearn.datasets.base.Bunch

In [5]:
boston

{'DESCR': "Boston House Prices dataset\n===========================\n\nNotes\n------\nData Set Characteristics:  \n\n    :Number of Instances: 506 \n\n    :Number of Attributes: 13 numeric/categorical predictive\n    \n    :Median Value (attribute 14) is usually the target\n\n    :Attribute Information (in order):\n        - CRIM     per capita crime rate by town\n        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.\n        - INDUS    proportion of non-retail business acres per town\n        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)\n        - NOX      nitric oxides concentration (parts per 10 million)\n        - RM       average number of rooms per dwelling\n        - AGE      proportion of owner-occupied units built prior to 1940\n        - DIS      weighted distances to five Boston employment centres\n        - RAD      index of accessibility to radial highways\n        - TAX      full-value property-tax rate per

1. CRIM: per capita crime rate by town 
2. ZN: proportion of residential land zoned for lots over 25,000 sq.ft. 
3. INDUS: proportion of non-retail business acres per town 
4. CHAS: Charles River dummy variable (= 1 if tract bounds river; 0 otherwise) 
5. NOX: nitric oxides concentration (parts per 10 million) 
6. RM: average number of rooms per dwelling 
7. AGE: proportion of owner-occupied units built prior to 1940 
8. DIS: weighted distances to five Boston employment centres 
9. RAD: index of accessibility to radial highways 
10. TAX: full-value property-tax rate per $10,000 
11. PTRATIO: pupil-teacher ratio by town 
12. B: 1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town 
13. LSTAT: % lower status of the population 
14. MEDV: Median value of owner-occupied homes in $1000's

In [6]:
df = pd.DataFrame(boston.data, columns = boston.feature_names)
df["MEDV"] = boston.target
df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  MEDV  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     17.8  392.83   4.03  34.7  
3     18.7  394.63   2.94  33.4  
4     18.7  396.90   5.33  36.2

In [7]:
boston.data[0]

array([  6.32000000e-03,   1.80000000e+01,   2.31000000e+00,
         0.00000000e+00,   5.38000000e-01,   6.57500000e+00,
         6.52000000e+01,   4.09000000e+00,   1.00000000e+00,
         2.96000000e+02,   1.53000000e+01,   3.96900000e+02,
         4.98000000e+00])

### 訓練樣本與測試樣本

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
X_train, X_test, y_train, y_test = train_test_split(boston.data,boston.target, test_size =0.25, random_state = 33 )

### 表準化

In [11]:
from sklearn.preprocessing import StandardScaler

In [12]:
scalerX = StandardScaler().fit(X_train)
scalery = StandardScaler().fit(y_train.reshape(-1,1))

In [13]:
X_train = scalerX.transform(X_train) # Perform standardization
y_train = scalery.transform(y_train.reshape(-1,1))
X_test = scalerX.transform(X_test)
y_test = scalery.transform(y_test.reshape(-1,1))

### 建立回歸模型

In [14]:
from sklearn import linear_model

In [15]:
clf_sgd = linear_model.SGDRegressor(loss='squared_loss', penalty=None,  random_state=42)

In [16]:
clf_sgd.fit(X_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:526: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SGDRegressor(alpha=0.0001, average=False, epsilon=0.1, eta0=0.01,
       fit_intercept=True, l1_ratio=0.15, learning_rate='invscaling',
       loss='squared_loss', n_iter=5, penalty=None, power_t=0.25,
       random_state=42, shuffle=True, verbose=0, warm_start=False)

### Evaluation
Regression evaluation methods:
1. mean absolute error
2. mean squared error
3. median absolute error
4. R2(coeifficient of determination)


* scoring parameter

In [25]:
from sklearn.cross_validation import KFold
from sklearn.model_selection import cross_val_score

In [49]:
cv =KFold(X_train.shape[0], 5, shuffle =True, random_state = 33)
scores = cross_val_score(clf_sgd ,X_train, y_train, scoring = "mean_squared_error", cv=cv)
print(scores)

[-0.18867133 -0.32514721 -0.54189059 -0.16463756 -0.2636966 ]


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:526: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\scorer.py:90: DeprecationWarning: Scoring method mean_squared_error was renamed to neg_mean_squared_error in version 0.18 and will be removed in 0.20.
  sample_weight=sample_weight)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:526: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\scorer.py:90: DeprecationWarning: Scoring method mean_squared_error was renamed to neg_mean_squared_error in version 0.18 and will be removed in 0.20.
  sample_weight=sam

In [27]:
scores = cross_val_score(clf_sgd ,X_train, y_train)
print (scores)

[ 0.75079823  0.5720941   0.76471841]


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:526: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:526: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:526: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


* Estimator score method

In [35]:
print(clf_sgd.score(X_train, y_train))
print(clf_sgd.score(X_test, y_test))

0.743617732983
0.64964456173


* Metric functions

In [36]:
from sklearn import metrics

In [38]:
y_pred = clf_sgd.predict(X_test)

In [44]:
print(metrics.mean_absolute_error(y_test,y_pred))
print(metrics.mean_squared_error(y_test,y_pred))
print(metrics.median_absolute_error(y_test,y_pred))
print(metrics.r2_score(y_test,y_pred))

0.380130815937
0.315471907879
0.280903568018
0.64964456173


模型係數

In [27]:
clf_sgd.coef_

array([-0.08527595,  0.06706144, -0.05032898,  0.10874804, -0.07755151,
        0.38961893, -0.02485839, -0.20990016,  0.08491659, -0.05495108,
       -0.19854006,  0.06126093, -0.37817963])

In [19]:
clf_sgd_12 = linear_model.SGDRegressor(loss='squared_loss', penalty="l2",  random_state=42)

In [28]:
from IPython.display import Image
Image(url="https://docs.microsoft.com/zh-tw/azure/machine-learning/media/machine-learning-evaluate-model-performance/2.png", width=400, height=400)